### ISSUE TITLE
Breaking Change in 1.5.2

### ISSUE THREAD

**Issue by firta4** [leroyguillaume/keycloak-bcrypt#33]
Hi,

I just tried migrating from 1.5.1 to 1.5.2 and noticed that credentials created with 1.5.1 are invalid when checked with 1.5.2.

I have a docker compose yml for setting up a Keycloak (20.0.3) and a postgres locally. I tried the following scenarios:
1.
Starting Keycloak (20.0.3) with keycloak-bcrypt 1.5.2 and postgres-db, importing realms (created with 20.0.3). Registering user. => Login works.

2. 
Starting Keycloak (20.0.3) with keycloak-bcrypt 1.5.1 and postgres-db, initially importing realms and users from JSON (created with Keycloak 20.0.3 and keycloak-bcrypt 1.5.1).
=> Logins work.
Stopping Keycloak-Container and starting Keylcoak-Container with keycloak-bcrypt 1.5.2.
=> For already existing users I get LOGIN_ERROR. Registering new users works. Login with new users works too.

3.
Starting Keycloak (20.0.3) with keycloak-bcrypt 1.5.2 and postgres-db, initially importing realms and users from JSON (created with Keycloak 20.0.3 and keycloak-bcrypt 1.5.1).
=> For already existing users I get LOGIN_ERROR. Registering new users works. Login with new users works too.

My Keycloak is configured to use 12 Hashing Iterations.
The password data of the users credentials whether imported or registered, show the same information.

Now my question is: Is this a bug or am I missing configuration changes?

Any assistance would be greatly appreciated.

**Comment by leroyguillaume** [comment]
Hello!

Thanks for the report. 

It seems it is a bug yes... I need to investigate but it seems to come from the verifier. You can still continue the 1.5.1 for the moment and I keep you in touch when a new version that fixes this issue is released. 

@mathieutu can you send to me a dummy pre-hashed password to see the format of the hash and try to find a way to determine the verifier?

**Comment by leroyguillaume** [comment]
Hello @firta4 

What is the version of BCrypt hashes that don't work anymore?

**Comment by firta4** [comment]
Hello @leroyguillaume 

The BCrypt hashes created from a Keycloak 20.0.3 with keycloak-bcrypt 1.5.1, that don't work in Keycloak 20.0.3 with keycloak-bcrypt 1.5.2, are $2y$ hashes. Newly registered users with therefore newly generated hashes that do work are also $2y$.
Does that answer your question?

**Comment by mathieutu** [comment]
@firta4 Could you share one of your password please (ofc a dummy one, like `qwerty`)?
- raw
- encrypted with 1.5.1
- encrypted with 1.5.2


@leroyguillaume:
Raw password: `kGKdj2z01GeBrtB7JKTOJxBCHxMshUO7BsJpocwt8YXl1nU5mEc8DXq6rVYtA+1T1+v7Ke8r`
Encrypted one: `$2b$12$FWUE6.0P.3GwjqZGzakHhuD0dpTPtC41unb6SilBNVPgFOVhjts5K`

(yep our passwords are originally issued in 2b version, but all the versions are compatible so 🤷.)

I've also noticed that a new password generated with this 1.5.2 version does not pass a standard [bcryp verifier](https://bcrypt.online/). It seems to have something broken with the bcrypt package with this version.

<details>
<summary>Example created directly in keycloak with 1.5.2</summary>
pwd: `azerty`
hash: `$2y$12$Vq6f3ZhnptGlrFlPS/qTNORRwRstCzDQinmbaNFxbwTAgdnRSAHee`
</details>

I'm currently digging into the bcrypt package code to understand where it could come from.

**Comment by firta4** [comment]
Hello @mathieutu 

this is one of them:

Raw: `jmeter13`
1.5.1: `$2y$12$meAfhbSMFKN3cDk/OZCtme2XQk5cr9a7Nro34fVJEdyPUot2rtvbq`
1.5.2: `$2y$12$u.b5C8W22qoJh58GrN4kje0CAofrZ0AXBgi4WJ1jcVP5eHjOUaJSS`

**Comment by mathieutu** [comment]
From what I understood, it seems to come from [here](https://github.com/patrickfav/bcrypt/blob/f387266a305937f2d0450e2e57c7f5d2843a4863/modules/bcrypt/src/main/java/at/favre/lib/crypto/bcrypt/BCrypt.java#L306).

This package seems to have an original way to handle long passwords, and the null terminator byte (seeing all the [issues](https://github.com/patrickfav/bcrypt/issues?q=is%3Aissue+sort%3Aupdated-desc+) about this topic).

They actually created the `VERSION_2Y_NO_NULL_TERMINATOR` because of a compatibility issue with php passwords.

I'm thinking about two choices:
- Using a basic version instead of this custom one:
```diff
new Version(new byte[]{MAJOR_VERSION, 0x79}, true, false, MAX_PW_LENGTH_BYTE, DEFAULT_FORMATTER, DEFAULT_PARSER);
new Version(new byte[]{MAJOR_VERSION, 0x79}, true, true, MAX_PW_LENGTH_BYTE, DEFAULT_FORMATTER, DEFAULT_PARSER);
```
- Use the `LongPasswordStrategies.none` strategy, to disable totally the warning about long passwords, and let bcrypt handles the hash with its standard behaviour (truncate the password after 72 bytes) (it seems to be the way of doing of all other implementations)


BTW, not specially related @leroyguillaume, but why did you choose to generate password with `2Y` version instead of standard one?
(`2Y` is the specific version of php generated passwords (to go along with `2x` ones), but the verifier doesn't care about the version number. Generating standard 2a or 2b passwords would still allow 2y ones.)

**Comment by mathieutu** [comment]
I've opened [an issue](https://github.com/patrickfav/bcrypt/issues/43) in the package.

**Comment by leroyguillaume** [comment]
@mathieutu thnk you very much for your help on this topic!

> BTW, not specially related @leroyguillaume, but why did you choose to generate password with 2Y version instead of standard one?
It's a long time ago... I wrote this module to import a legacy database of users managed by Symfony, so I think this is why. But honestly I didn't think about the version of BCrypt at that time... 😅

**Comment by quinot** [comment]
@mathieutu I believe @leroyguillaume should indeed revert #32
* as @firta4 identified, this is an incompatible change for shorter passwords, as the NUL terminator then comes into play when expanding the short password to 72 bytes of data (as a matter of fact, the hash value shown for 1.5.2 can be verified with another implementation by manually doing the cyclic repetition e.g. with python: `bcrypt.checkpw(b"jmeter13" * 9, b"$2y$12$u.b5C8W22qoJh58GrN4kje0CAofrZ0AXBgi4WJ1jcVP5eHjOUaJSS")` is True
* the correct fix is in the upstream brypt implementation (patrickfav/bcrypt#44).
* with that fix applied, the bcrypt CLI tool verifies our hash correctly:

```
$ java -jar ./modules/bcrypt-cli/target/bcrypt-cli-0.10.0-full.jar 'kGKdj2z01GeBrtB7JKTOJxBCHxMshUO7BsJpocwt8YXl1nU5mEc8DXq6rVYtA+1T1+v7Ke8r' -c '$2b$12$FWUE6.0P.3GwjqZGzakHhuD0dpTPtC41unb6SilBNVPgFOVhjts5K'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/home/quinot/projects/bcrypt/modules/bcrypt-cli/target/bcrypt-cli-0.10.0-full.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Hash verified.
```

**Comment by mathieutu** [comment]
The [PR](https://github.com/leroyguillaume/keycloak-bcrypt/pull/34) is done!
